#!/bin/bash

newVersion=""

LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)

if [[ "$LAST_COMMIT_MESSAGE" != *"Update version"* ]]; then
  echo "Automated commit message not found. Updating..."

  newVersion=$(deno task version)
  if [ $? -ne 0 ]; then
    echo "Version update failed. Please check the issue and try again."
    exit 1
  fi

  git add ./deno.json
  if [ $? -ne 0 ]; then
    echo "Failed to stage updated files. Please check the issue and try again."
    exit 1
  fi

  git commit -m "Update version to ${newVersion}"
  if [ $? -ne 0 ]; then
    echo "Failed to create a commit. Please check the issue and try again."
    exit 1
  fi

  git tag -a "v${newVersion}" -m "Version v${newVersion}"
  if [ $? -ne 0 ]; then
    echo "Failed to create Git tag. Please check the issue and try again."
    exit 1
  fi

  echo "Updated to v${newVersion}. Push again."
  exit 1
fi

deno fmt --check

if [ $? -ne 0 ]; then
  echo "Formatting failed. Please fix the issues and try again."
  exit 1
fi

deno lint

if [ $? -ne 0 ]; then
  echo "Linting failed. Please fix the issues and try again."
  exit 1
fi

deno test --no-check

if [ $? -ne 0 ]; then
  echo "Tests failed. Please fix the issues and try again."
  exit 1
fi

# Ensure newVersion is accessible at the end of the script
if [ -n "$newVersion" ]; then
  git tag -a "v$newVersion" -m "Version v$newVersion"
  git push origin "v$newVersion"
else
  echo "Version variable is empty! Ensure it was correctly set."
fi

exit 0
